package lt.verbus.repository;

import lt.verbus.model.User;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

public class UserRepository {

    private final Connection connection;
    private final Statement statement;
    private PreparedStatement preparedStatement;

    public UserRepository(Connection connection, Statement statement) {
        this.connection = connection;
        this.statement = statement;
    }

    public User save(User user){
        //TODO: Save user to database and return updated instance with autogenerated id
        return null;
    }

}
